fix

diff --git a/.github/workflows/release-push.yaml b/.github/workflows/release-push.yaml
--- a/.github/workflows/release-push.yaml
+++ b/.github/workflows/release-push.yaml
@@ -89,7 +89,9 @@ jobs:
           new_version="$(semver bump patch $version)"
           echo "::set-output name=new_version::${new_version}"
           sed -Ei "s/(version[[:space:]]*=[[:space:]]*)\"${version}\"/\1\"${new_version}\"/" $file
-          git diff $file # For debugging.
+          if [[ ! git diff --exit-code $file ]] ; then
+            echo "error: no changes in \"$file\"" >&2
+          fi
       - name: Commit changes
         run: |
           git config --local user.email "action@github.com"
