Groups, validation

diff --git a/.github/workflows/zz_generated.create_release_pr.yaml b/.github/workflows/zz_generated.create_release_pr.yaml
--- a/.github/workflows/zz_generated.create_release_pr.yaml
+++ b/.github/workflows/zz_generated.create_release_pr.yaml
@@ -25,40 +25,46 @@ jobs:
     name: Gather facts
     runs-on: ubuntu-18.04
     outputs:
-      unchanged: ${{ steps.get_unchanged.outputs.unchanged }}
-      base: ${{ steps.get_base.outputs.base }}
-      version: ${{ steps.get_version.outputs.version }}
+      base: ${{ steps.get_info.outputs.base }}
+      version: ${{ steps.get_info.outputs.version }}
     steps:
-      - name: Get base
-        id: get_base
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Get base, head & version
+        id: get_info
         run: |
-          base="$(echo ${{ github.event.ref }} | cut -d '#' -f 1)"
-          echo "base=\"$base\""
-          echo "::set-output name=base::${base}"
-      - name: Get version
-        id: get_version
-        run: |
-          version="$(echo ${{ github.event.ref }} | cut -d '#' -f 3)"
+          echo "::group::Get info"
+          head="${{ github.event.ref }}"
+          head="${head#refs/heads/}" # Strip "refs/heads/" prefix.
+          base="$(echo $head | cut -d '#' -f 1)"
+          base="${base#refs/heads/}" # Strip "refs/heads/" prefix.
+          version="$(echo $head | cut -d '#' -f 3)"
           version="${version#v}" # Strip "v" prefix.
-          echo "version=\"$version\""
+          echo "::endgroup::"
+          echo "::group::Validate"
+          git rev-list --left-right --count origin/$base...origin/$head
+          echo "::endgroup::"
+          echo "::group::Set outputs"
+          echo "base=\"$base\" head=\"$head\" version=\"$version\""
+          echo "::set-output name=base::${base}"
+          echo "::set-output name=head::${head}"
           echo "::set-output name=version::${version}"
+          echo "::endgroup::"
       - name: Checkout base code
         uses: actions/checkout@v2
         with:
-          ref: ${{ steps.get_base.outputs.base }}
-      - name: Get unchanged
-        id: get_unchanged
+          ref: ${{ steps.get_info.outputs.base }}
+      - name: Check if not behind base
         env:
-          sha: ${{ github.sha }}
+          base: ${{ steps.get_info.outputs.base }}
+          head: ${{ steps.get_info.outputs.head }}
         run: |
-          base_head=$(git rev-parse HEAD)
-          echo "base_head=\"$base_head\""
-          unchanged="false"
-          if [[ "$base_head" == "${{ env.sha }}" ]] ; then
-            unchanged="true"
+          base_sha=$(git rev-parse HEAD)
+          echo "base_sha=\"$base_sha\""
+          if [[ "$base_sha" == "${{ github.sha }}" ]] ; then
+            echo "::error:: Head branch ${{ env.head }} HEAD ($base_head) is behind base branch ${{ env.base }} HEAD (${{ github.sha }}). Please recreate the ${{ env.bas }} branch."
+            exit 1
           fi
-          echo "unchanged=\"$unchanged\""
-          echo "::set-output name=unchanged::${unchanged}"
   install_architect:
     name: Install architect
     runs-on: ubuntu-18.04
@@ -100,7 +106,6 @@ jobs:
   create_release_pr:
     name: Create release PR
     runs-on: ubuntu-18.04
-    if: ${{ needs.gather_facts.outputs.unchanged == 'true' }}
     needs:
       - gather_facts
       - install_architect
